[package]
name = "zhang_hilbert"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
num = { version = "0.2.0", default-features = false }
array = "0.0.1"
bitflags = "1.0.4"
flags-macro = "0.1.3"

[dev-dependencies]
ndarray = "0.12.1"
